//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCTNEntities : DbContext
    {
        public BCTNEntities()
            : base("name=BCTNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<binhluan> binhluans { get; set; }
        public virtual DbSet<bonho> bonhoes { get; set; }
        public virtual DbSet<cameraSau> cameraSaus { get; set; }
        public virtual DbSet<cameraTruoc> cameraTruocs { get; set; }
        public virtual DbSet<chitietsanpham> chitietsanphams { get; set; }
        public virtual DbSet<donhang> donhangs { get; set; }
        public virtual DbSet<giohang> giohangs { get; set; }
        public virtual DbSet<hedieuhanh> hedieuhanhs { get; set; }
        public virtual DbSet<ketnoi> ketnois { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<manhinh> manhinhs { get; set; }
        public virtual DbSet<muahang> muahangs { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<thietketrongluong> thietketrongluongs { get; set; }
        public virtual DbSet<thongtin> thongtins { get; set; }
        public virtual DbSet<thongtinsac> thongtinsacs { get; set; }
        public virtual DbSet<Tienich> Tieniches { get; set; }
        public virtual DbSet<yeuthich> yeuthiches { get; set; }
    }
}
