//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bonho
    {
        public int id { get; set; }
        public Nullable<int> maSp { get; set; }
        public string tensp { get; set; }
        public string ram { get; set; }
        public string bonhotrong { get; set; }
        public string bonhokhadung { get; set; }
        public string thenhongoai { get; set; }
        public string hotrothetoida { get; set; }
    }
}
