//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cameraSau
    {
        public int id { get; set; }
        public Nullable<int> maSp { get; set; }
        public string tensp { get; set; }
        public string dophangiai { get; set; }
        public string quayphim { get; set; }
        public string denflash { get; set; }
        public string chupanhnangcao { get; set; }
    }
}
