//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietsanpham
    {
        public int id { get; set; }
        public Nullable<int> masp { get; set; }
        public string mausp { get; set; }
        public string mota { get; set; }
        public string hinh87x113 { get; set; }
        public string hinh270x281 { get; set; }
        public string hinh270x290 { get; set; }
        public string hinh270x307 { get; set; }
        public string hinh270x357 { get; set; }
        public string hinh277x290 { get; set; }
        public string hinh315x255 { get; set; }
        public string hinh320x240 { get; set; }
        public string hinh320x320 { get; set; }
        public string hinh355x212 { get; set; }
        public string hinh370x285 { get; set; }
        public string hinh370x420 { get; set; }
        public string hinh370x600 { get; set; }
        public string hinh378x238 { get; set; }
        public string hinh400x300 { get; set; }
        public string hinh435x265 { get; set; }
        public string hinh445x265 { get; set; }
        public string hinh565x480 { get; set; }
        public string hinh565x566 { get; set; }
        public string hinh570x437 { get; set; }
        public string hinh570x603 { get; set; }
        public string hinh582x343 { get; set; }
        public string hinh592x378 { get; set; }
        public string hinh240x190 { get; set; }
    }
}
