//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donhang
    {
        public int madh { get; set; }
        public int makh { get; set; }
        public string thanhtoan { get; set; }
        public string tinhtranggiaohang { get; set; }
        public Nullable<System.DateTime> ngaydat { get; set; }
        public Nullable<System.DateTime> ngaygiao { get; set; }
    }
}
