//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sanpham
    {
        public int masp { get; set; }
        [Required(ErrorMessage = "Nhập tên sản phẩm")]
        public string tensp { get; set; }
        [Required(ErrorMessage = "Nhập mã loại sản phẩm")]
        public string MaLSP { get; set; }
        [Required(ErrorMessage = "Nhập giá")]
        public Nullable<int> gia { get; set; }
        [Required(ErrorMessage = "Nhập đơn vị")]
        public string donvi { get; set; }
        [Required(ErrorMessage = "Nhập mô tả")]
        public string mota { get; set; }
        [Required(ErrorMessage = "Nhập số lượng sản phẩm")]
        public Nullable<int> slsp { get; set; }
        public Nullable<int> trangthai { get; set; }
    }
}
