//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int makh { get; set; }
        public string TenDangnhap { get; set; }
        public string Ten { get; set; }
        public string Ho { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
        public string Matkhau { get; set; }
        public Nullable<int> Phanquyen { get; set; }
    }
}
