//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtinsac
    {
        public int id { get; set; }
        public Nullable<int> maSp { get; set; }
        public string tensp { get; set; }
        public string dungluongpin { get; set; }
        public string loaipin { get; set; }
        public string congnghePin { get; set; }
    }
}
