//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tienich
    {
        public int id { get; set; }
        public Nullable<int> maSp { get; set; }
        public string tensp { get; set; }
        public string baomatnangcao { get; set; }
        public string tinhnangdacbiet { get; set; }
        public string ghiam { get; set; }
        public string radio { get; set; }
        public string xemphim { get; set; }
        public string nghenhac { get; set; }
    }
}
